### ISSUE TITLE
Installataion triggers QA issues

### ISSUE THREAD

**Issue by Lucretia** [Lucretia/ada-overlay#1]
- PT_PAX marking -r /var/tmp/portage/sys-devel/gcc-4.9.3/image//usr/libexec/gcc/i686-pc-linux-gnu/4.9.3/cc1 with scanelf
- XATTR_PAX marking -re /var/tmp/portage/sys-devel/gcc-4.9.3/image//usr/libexec/gcc/i686-pc-linux-gnu/4.9.3/cc1 with setfattr
- PT_PAX marking -r /var/tmp/portage/sys-devel/gcc-4.9.3/image//usr/libexec/gcc/i686-pc-linux-gnu/4.9.3/cc1plus with scanelf
- XATTR_PAX marking -re /var/tmp/portage/sys-devel/gcc-4.9.3/image//usr/libexec/gcc/i686-pc-linux-gnu/4.9.3/cc1plus with setfattr
  >>> Completed installing gcc-4.9.3 into /var/tmp/portage/sys-devel/gcc-4.9.3/image/

Auto fixing rpaths for /var/tmp/portage/sys-devel/gcc-4.9.3/image/usr/lib/gcc/i686-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
- QA Notice: The following files contain insecure RUNPATHs
-  Please file a bug about this at http://bugs.gentoo.org/
-  with the maintaining herd of the package.
-   /var/tmp/portage/sys-devel/gcc-4.9.3/image/usr/lib/gcc/i686-pc-linux-gnu/4.9.3/libstdc++.so.6.0.20
- QA Notice: The following files contain writable and executable sections
-  Files with such sections will not work properly (or at all!) on some
-  architectures/operating systems.  A bug should be filed at
-  http://bugs.gentoo.org/ to make sure the issue is fixed.
-  For more information, see:
- 
-    https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
- 
-  Please include the following list of files in your report:
-  Note: Bugs should be filed for the respective maintainers
-  of the package in question and not hardened@g.o.
- RWX --- --- usr/i686-pc-linux-gnu/gcc-bin/4.9.3/gnatls
- RWX --- --- usr/i686-pc-linux-gnu/gcc-bin/4.9.3/gnatname
- RWX --- --- usr/i686-pc-linux-gnu/gcc-bin/4.9.3/gnat
- RWX --- --- usr/i686-pc-linux-gnu/gcc-bin/4.9.3/gnatmake
- RWX --- --- usr/i686-pc-linux-gnu/gcc-bin/4.9.3/gnatclean
- QA Notice: Package triggers severe warnings which indicate that it
-            may exhibit random runtime failures.
- cal.c:108:3: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
- socket.c:154:3: warning: implicit declaration of function ‘pipe’ [-Wimplicit-function-declaration]
- socket.c:164:3: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
- socket.c:174:3: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
- socket.c:182:3: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
- terminals.c:1182:21: warning: argument to ‘sizeof’ in ‘bzero’ call is the same expression as the destination; did you mean to remove the addressof? [-Wsizeof-pointer-memaccess]
- g-expect.adb:1341:7: warning: ‘INPUT’ is used uninitialized in this function [-Wuninitialized]
- g-expect.adb:1342:7: warning: ‘OUTPUT’ is used uninitialized in this function [-Wuninitialized]
- g-expect.adb:1343:7: warning: ‘ERROR’ is used uninitialized in this function [-Wuninitialized]
- cal.c:108:3: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
- socket.c:154:3: warning: implicit declaration of function ‘pipe’ [-Wimplicit-function-declaration]
- socket.c:164:3: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
- socket.c:174:3: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
- socket.c:182:3: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
- terminals.c:1182:21: warning: argument to ‘sizeof’ in ‘bzero’ call is the same expression as the destination; did you mean to remove the addressof? [-Wsizeof-pointer-memaccess]
- g-expect.adb:1341:7: warning: ‘INPUT’ is used uninitialized in this function [-Wuninitialized]
- g-expect.adb:1342:7: warning: ‘OUTPUT’ is used uninitialized in this function [-Wuninitialized]
- g-expect.adb:1343:7: warning: ‘ERROR’ is used uninitialized in this function [-Wuninitialized]

**Comment by sarnold** [comment]
This should be mitigated/fixed now, can you test it?  Note 7.x upstream has fixed the trampoline warnings, 6.x is as good as it gets.
