### ISSUE TITLE
Installing gcc with ada from bootstrap fails in compiling a-charac.ads

### ISSUE THREAD

**Issue by kwohlfahrt** [Lucretia/ada-overlay#4]
Installing sys-devel/gcc from the this overlay (with gcc `5.4.0-r3` installed from gentoo repos) fails with the error below (`a-charac.ads:16:01: user-defined descendents of package Ada are not allowed`).

This is using paludis as the package manager, but the error happens when the included command is run on its own as well.

```
/var/tmp/paludis/sys-devel-gcc-6.4.0/work/gnat_bootstrap/usr/bin/gcc -c   -O2 -march=native -fomit-frame-pointer -pipe  -W -Wall -nostdinc -I- -I. -Iada/generated -Iada -I/var/tmp/paludis/sys-devel-gcc-6.4.0/work/gcc-6.4.0/gcc/ada -I/var/tmp/paludis/sys-devel-gcc-6.4.0/work/gcc-6.4.0/gcc/ada/gcc-interface /var/tmp/paludis/sys-devel-gcc-6.4.0/work/gcc-6.4.0/gcc/ada/a-charac.ads -o ada/a-charac.o

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =sys-devel/gcc-6.4.0:6.4.0::ada --destination installed --x-of-y 1 of 1:
  * When installing 'sys-devel/gcc-6.4.0:6.4.0::ada':
  * When running an ebuild command on 'sys-devel/gcc-6.4.0:6.4.0::ada':
  * Install failed for 'sys-devel/gcc-6.4.0:6.4.0::ada' (paludis::ActionFailedError)

make[3]: Leaving directory '/var/tmp/paludis/sys-devel-gcc-6.4.0/work/build/gcc'
make[2]: Leaving directory '/var/tmp/paludis/sys-devel-gcc-6.4.0/work/build'
make[1]: Leaving directory '/var/tmp/paludis/sys-devel-gcc-6.4.0/work/build'
a-charac.ads:16:01: user-defined descendents of package Ada are not allowed
make[3]: *** [/var/tmp/paludis/sys-devel-gcc-6.4.0/work/gcc-6.4.0/gcc/ada/gcc-interface/Make-lang.in:123: ada/a-charac.o] Error 1
make[2]: *** [Makefile:4388: all-stage1-gcc] Error 2
make[1]: *** [Makefile:20904: stage1-bubble] Error 2
make: *** [Makefile:21236: bootstrap-lean] Error 2

!!! ERROR in sys-devel/gcc-6.4.0::ada:
!!! In /usr/libexec/paludis/utils/emake at line 30
!!! emake returned error 2

!!! Call stack:
!!!    * paludis_die_or_error_func (/usr/libexec/paludis/die_functions.bash:82)
!!!    * main (/usr/libexec/paludis/utils/emake:30)

diefunc: making ebuild PID 13864 exit with error
die trap: exiting with error.
```

**Comment by kwohlfahrt** [comment]
Comparing to the command from `gnat-gpl`, that succeeds, that also defines the `-gnatpg` and `-gnatwns` flags. The former seems to be necessary.

**Comment by kwohlfahrt** [comment]
Nevermind, I still had `ADAFLAGS` environment variable defined from when I was using `gnat-gpl`, and this was breaking things. Though perhaps these should be overridden?

**Comment by gerr135** [comment]
I am hitting this issue too. This is on a completely fresh install, straight from stage3 only rebuilt gcc (active version 7.3.0) and run emerge world -e to make the system consistent. Overlay installed using layman (by adding that URL as described). gcc rebuilt 1 time following addition of an overlay.  gcc::portage (7.3.0) rebuilt fine, but then gcc::ada (7.2.0) emerge fails rather quickly with exactly the same complaint (as well citing other .ads files). No prior traces of Ada/gnat on the system in any form. "set|grep ADA" returns empty to..  NOTE: I was getting the same failure on a "regular" system when trying to switch from gnat-gpl (which built fine) to gcc::ada, thus all that extra testing on completely fresh system (in chroot).
Let me know if you want me to post any info here (but that would be the same as above I suppose) or open a bug on bugs.gentoo.org
George

**Comment by Lucretia** [comment]
This isn't officially in gentoo yet, so they'll close the bug.

Can you upload The build log?

ping @sarnold
