### ISSUE TITLE
asking for update or help

### ISSUE THREAD

**Issue by gch1p** [Lucretia/ada-overlay#5]
Hi! 
gcc-7.2.0-r1 no longer builds because gcc-7.2.0-patches-1.1.tar.bz2 file no longer exists ("404 Not Found" when emerge is trying to download it). Could you please update it to the current gcc versions used in Gentoo, or tell me how/what's required to do that? As I understand it's not just copy-pasting ebuilds, and I'm not yet familiar with Ada and how it works in Gentoo.

**Comment by Lucretia** [comment]
It's not that simple. We need new cross compilers which are built statically, this is because there were abi changes. Then the eclass in this overlay needs updating.

**Comment by Lucretia** [comment]
A little bit more info, I didn't build these compilers, they were built so they linked dynamically to the base maths libs, so when they changed the bootstraps failed to work. This is why these need to be built statically.

I take it you're on x86-64? I could probably get a bootstrap built for that one target and uploaded here or somewhere else. I'm not a gentoo dev, so I don't have an account there.

**Comment by gch1p** [comment]
Yes, I'm on x86-64. Thank you, that would be helpful. Or you can just share some... I don't know, a script template, or some kind of algorithm that explains how to build them so that I or someone else could build it too and not bother you :)

**Comment by Lucretia** [comment]
yeah, having this as part of the this overlay would be useful, tbh.
