### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by catfromplan9** [Lucretia/ada-overlay#7]
!!! A file listed in the Manifest could not be found: /var/db/repos/ada/sys-devel/gcc/files/gcc-14.0.0_pre20231001-pgo-bootstrap.patch

**Comment by Lucretia** [comment]
Don't know what happened, the scripts are usually pretty good are removing all the old stuff.

Fixed with 2fa31bb023fcc78f15603177e2caa740b9cd2a95
